[package]
name = "deoos-node"
version = "0.7.1"
edition = "2024"
license = "Apache-2.0"
description = "Durable execution on object storage."
[lib]
crate-type = ["cdylib"]
[dependencies]
deoos-engine = { path = "../../engine" }
napi = { version = "3", features = ["tokio_rt", "napi8"] }
napi-derive = "3"
serde_json = "1"
